### PR TITLE
README: Put icons into tables, cleanups

### PR DESCRIPTION
**Pull request by sschuberth**

### CODE REVIEW

**Comment by sschuberth** [comment]
@ovinn Would you mind having a look?

**Comment by oleg-nenashev** [comment]
:+1: from what I see. Just  a refactoring, but it may be useful

**Comment by sschuberth** [comment]
It's a bit more than refactoring: It also adds the "disabled build" icon to the legend which was not there before.

**Comment by sschuberth** [comment]
@oleg-nenashev So I had mailed @ovinn privately two weeks ago, no response. Can you merge on his behalf, or allow me to merge?

**Comment by ghost** [comment]
Hi @oleg-nenashev and @sschuberth sorry for the long wait. Thanks for taking time to clean up.

**Pull request merged**
